name: "Pull Request Checks"

on:
  pull_request:
    branches: [ main ]
    #paths:
    #  - 'java/**'

jobs:
  build-and-test-packs:
    name: Build and Test CodeQL Packs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Test
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         gh extensions install github/gh-codeql
         gh extensions install zbazztian/gh-tailor
         gh codeql download latest
         gh codeql set-version latest
         ./tests.sh "${{ matrix.language }}"
