name: "Publish"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  determine-actions-cli-version:
    name: Determine CLI version installed in Actions
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cliversion.outputs.v }}
    steps:
    - id: downloadcli
      uses: github/codeql-action/init@v2
    - id: cliversion
      shell: bash
      run: |
        VERSION="${{ steps.downloadcli.outputs.codeql-path }}" version -q
        echo "$VERSION"
        echo "::set-output name=v::$VERSION"

  build-and-test-packs:
    name: Build, Test and Publish CodeQL Packs
    runs-on: ubuntu-latest
    needs: determine-actions-cli-version

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build, Test and Publish
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         echo "howdy"
         echo ${{ needs.determine-actions-cli-version.outputs.version }}
         gh extensions install github/gh-codeql
         gh extensions install zbazztian/gh-tailor
         gh codeql download latest
         gh codeql set-version latest
         ./tests.sh "${{ matrix.language }}" --publish
